### ISSUE TITLE
Rival / Sensei 310 support

### ISSUE THREAD

**Issue by Sididi** [flozz/rivalcfg#37] opened 2017-10-09 14:44 UTC
Hi,

Is it troublesome for you to study the new steelseries products? I'd rly like to configure my 310 on my arch setup, as it's not working atm =)

**Comment by berkiyo** [comment] 2017-10-09 22:48
I would second this. The Rival 110 looks nice as it may be a future replacement for my current Rival 100. Who knows! 

I'd assume it's just a different hardware ID.

**Comment by flozz** [comment] 2017-10-10 07:02
Hi,

@Sididi The problem is not to study the mice itself, this should not be more difficult than the previous models. The problem is that I do not have the hardware (I cannot buy every new mouse they create), so I cannot do any reverse engineering on it... :(

@berkiyo It is possible to check if the Rival 110 has the same instruction set than an other mice, but I cannot check it my self, I have not bought this one.

**Comment by Sididi** [comment] 2017-10-10 07:06
I also reside in Lyon so based on where you exactly live, I can provide you a Sensei 310.
(A developer bro won't steal it anyway :smile: )

**Comment by flozz** [comment] 2017-10-10 07:10
Oh good news then :) 

I have to finish and release the new rivalcfg version, and then I can do some reverse engineering on your mouse if lend it to me for a few days :)

**Comment by Sididi** [comment] 2017-10-10 10:16
noice :smile: 
Tag me when you're available, I work around la part-dieu

**Comment by tomheady** [comment] 2017-10-13 22:06
I have added support for th Rival 310.

Here is the merge request: https://github.com/flozz/rivalcfg/pull/39

**Comment by DelusionalLogic** [comment] 2017-10-14 08:55
Changing sensitivity is properly supported in #38 

The color stuff demands a bit more analysis, but it doesn't seem that hard. The only thing that confuses me is that the color seems to be transmitted twice.

**Comment by flozz** [comment] 2017-10-14 13:31
The initial support of the Rival 310 has been merged in both `master` and `road-to-3-0-0-hidapi`.

I am currently working on CLI and API doc of rivalcfg in the `road-to-3-0-0-hidapi` branch, then I will be able to release the version 3.0.0 and to continue working on mice support :)

**Comment by tomheady** [comment] 2017-10-14 22:44
The colors are written twice, but it only uses the second color.

**Comment by tomheady** [comment] 2017-10-14 22:44
From what I can tell, the command for the wheel color is really long:
"command": [0x5b, 0x00, 0x01, 0x88, 0x13, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x01, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01],

**Comment by DelusionalLogic** [comment] 2017-10-15 00:44
I think those bytes are some sort of feature flags or something.

Interestingly the command for sensitivity also always ended with 0x00 0x42, but it worked fine even though I decided not to send that part. I don't know what that suffix does.

**Comment by flozz** [comment] 2017-10-15 09:52
It looks like the Rival 500 and 700 commands:

* https://github.com/flozz/rivalcfg/issues/32#issuecomment-304441751

It seems there is native support of color shifting by the mice

**Comment by phomes** [comment] 2017-10-15 12:11
Hi, just a heads up that I am working on support for the rival 310 in libratbag. Maybe we can learn from each others findings. I have a pretty good idea about the color modes although I have only implemented "solid" colors for now in the driver.

**Comment by flozz** [comment] 2017-10-15 12:21
I did not know about the libratbag project, it is very interesting :D 

> Maybe we can learn from each others findings.

Of course we should share any useful information. :)

**Comment by phomes** [comment] 2017-10-27 15:46
Hi again. I just added support for configuring the buttons on the 310. Feel free to ask any questions about the implementation:

https://github.com/libratbag/libratbag/commit/113bd4859e0437c8a5443c1aeaf4e6237f8e61bb

**Comment by phomes** [comment] 2018-02-07 00:16
I just wanted to give a heads up on the differences of the device firmware. I was adding support for the Sensei 310. It only started working correctly with my driver after I updated its firmware. So it seems that they changed/fixed the protocol in the new versions. I had already updated my Rival 310 before I started working on it, but I have gotten an issue report that the driver was not working for a users Rival 310. Just something keep in mind.

**Comment by FFY00** [comment] 2018-03-22 14:30
I just got a Rival 310. Is there anything I can help with? I've done re before.

**Comment by flozz** [comment] 2018-03-23 08:01
@FFY00 Hello,

You can help by testing this PR #43 (but you already found it :) ).

**Comment by Alexiwnl** [comment] 2018-12-25 05:35
> 
> 
> I just got a Rival 310. Is there anything I can help with? I've done re before.

I see you got a Rival 310 can you help me with something im not very experienced. I just got a rival 310 for christmas and i changed the led in the engine to color breath i selected the one with blue and yellow and now the mouse has only white led and if i try to change it back doesent do anything.

**Comment by Brog33** [comment] 2019-04-20 07:23
I have got a Rival 310 plugged in

`SteelSeries Rival 310 (Experimental)               1038:1720   (plugged)`

But these are the only options I get:
```
Options:
  --version             show program's version number and exit
  -h, --help            show this help message and exit
  -l, --list            print compatible mice and exit

  SteelSeries Rival 310 (Experimental) Options:
    -s SENSITIVITY1, --sensitivity1=SENSITIVITY1
                        Set sensitivity preset 1 (from 100 to 12000 in
                        increments of 100, default: 800)
    -S SENSITIVITY2, --sensitivity2=SENSITIVITY2
                        Set sensitivity preset 2 (from 100 to 12000 in
                        increments of 100, default: 1600)
    -r, --reset         Reset all options to their factory values
```
Rivalcfg won't let me adjust any of the settings of the Rival 300-series. Like when I try to change a color I get
`rivalcfg: error: no such option: -c`

Bug or feature? :P

**Comment by flozz** [comment] 2019-04-20 10:26
Hello, @Brog33 

The other options of the Rival 310 are not implemented. This is a PR (https://github.com/flozz/rivalcfg/pull/43) that contains more information. You can also try yo use the branch from this PR to configure more thing on your moues :)

**Comment by Brog33** [comment] 2019-04-20 11:10
> The other options of the Rival 310 are not implemented. This is a PR (#43) that contains more information. You can also try yo use the branch from this PR to configure more thing on your moues :)

Thanks, I tried it but the parameters for 310 to set color etc is missing from that branch too.
Question (offtopic?): If I use a windows machine, can I use it to turn off the mouse LED permanently - or will it just reset itself when it is plugged back into the Linux?

**Comment by flozz** [comment] 2019-04-20 12:23
> If I use a windows machine, can I use it to turn off the mouse LED permanently - or will it just reset itself when it is plugged back into the Linux?

The parameters are saved in the mouse memory. So if you setup the mouse on Windows, your config will be kept when you plug it back on your Linux :)

**Comment by Baxtex** [comment] 2019-06-04 12:06
I'd though the Rival and Sensei had similar hw but when I run `rivalcfg --logo-color=black --wheel-color=black` with my Sensei plugged i get an error saying command not found. What is requirered to make the Sensei work? I'm not an expert in Python but maybe I can help?

**Comment by flozz** [comment] 2020-01-30 11:55
Hello,

I am working on the support of the Sensei 310. A partial support will be available soon. If you want to test, there is some code in the [sensei-310](https://github.com/flozz/rivalcfg/tree/sensei-310) branch.

I close this issue because the discussion continued on #82 :)

**Closed by flozz** 2020-01-30 11:56 UTC
