### ISSUE TITLE
Aerox 3 wireless - Color's are not saving

### ISSUE THREAD

**Issue by ChocolatePie698** [flozz/rivalcfg#191] opened 2022-10-22 22:51 UTC
### Bug description
RGB color selections is not saving.
#### What happened

Changing colors seems to be fine at first but when the mouse disconnects or when the USB dongle disconnects, the RGB colors go back to what it was before.

#### What was expected

Turning off/disconnecting the mouse, and the colors stay the same before turning off/ disconnecting the mouse.

#### Step to reproduce

Change the z1, z2, and z3 colors to whatever. Turn off the mouse and watch rainbows come back.

→

### System information

```
RIVALCFG
========
Version: 4.7.0
udev rules installed: True
udev rules up to date: True
Installation path: /usr/lib/python3.10/site-packages/rivalcfg

OPERATING SYSTEM
================
OS: Linux
Platform: Linux-6.0.2-arch1-1-x86_64-with-glibc2.36
Version: #1 SMP PREEMPT_DYNAMIC Sat, 15 Oct 2022 14:00:49 +0000
Distribution issue: Arch Linux \r (\l)

PYTHON
======
Python version: 3.10.8
HIDAPI version: 0.12.0.post2

PLUGGED STEELSERIES DEVICES ENDPOINTS
=====================================
1038:1838 | 00 | SteelSeries Aerox 3 Wireless (firmware v0)
1038:1838 | 00 | SteelSeries Aerox 3 Wireless (firmware v0)
1038:1838 | 01 | SteelSeries Aerox 3 Wireless (firmware v0)
1038:1838 | 02 | SteelSeries Aerox 3 Wireless (firmware v0)
1038:1838 | 03 | SteelSeries Aerox 3 Wireless (firmware v0)
1038:1838 | 04 | SteelSeries Aerox 3 Wireless (firmware v0)
```

**Comment by flozz** [comment] 2022-10-23 10:02
Sadly, this is not a bug: on newer devices, colors are not saved anymore in the mouse memory... So it get back to the default (that can be a rainbow effect or off) :(

I will have to find a way to restore it automatically at startup, at wake up and when the device is plugged in...

**Comment by ChocolatePie698** [comment] 2022-10-24 02:48
Damn that's sad. I'm just used to mice storing lighting in memory. Thanks for letting me know on that.

**Comment by blurttextur** [comment] 2022-11-29 00:18
Is there a way to run rivalcfg as a daemon, so whenever the computer wakes up, or the mouse reconnects, the commands run again? 

I'm having the same issue, so I created a bash script to reset the color options (that runs at startup), but I'm not sure how to make it run whenever the mouse reconnects or the computer wakes up from idle.

**Comment by flozz** [comment] 2022-12-02 14:59
It is possible to run a command when a specific device is plugged to the computer using udev:

* https://www.thegeekdiary.com/how-to-run-a-script-when-usb-devices-is-attached-or-removed-using-udev/

But I do not think it will work for the wireless mice that wake up after IDLE as the USB dongle is never disconnected from the computer.

**Comment by wadhah101** [comment] 2022-12-31 10:43
Can confirm that this option is working on Aerox 3 


        The option is now on `master` for all devices that supports it (Aerox and Prime):

```
  -d DEFAULT_LIGHTING, --default-lighting DEFAULT_LIGHTING
                        Set default lighting at mouse startup (values: off, reactive,
                        rainbow, reactive-rainbow, default: rainbow)
```

I have to update the doc before releasing the new version :)

_Originally posted by @flozz in https://github.com/flozz/rivalcfg/issues/195#issuecomment-1365876881_
      
This issues should be marked as closed

**Comment by flozz** [comment] 2022-12-31 14:44
Thank you for the feedback :)

**Closed by flozz** 2022-12-31 14:44 UTC
Labels: bug
