### ISSUE TITLE
Rival 110 Unable to find the requested device

### ISSUE THREAD

**Issue by Konovalov-Nik** [flozz/rivalcfg#79] opened 2019-07-04 10:18 UTC
MacOS
I have rivalcfg installed from pip rivalcfg-3.6.0

I see the follwing error:
W: The following mouse was found but rivalcfg was not able to open it:
  * mouse: SteelSeries Rival 110 (1038:1729)
  * error: Unable to find the requested device: 1038:1729:00

The suggested unplug re-plug did not work.

**Comment by flozz** [comment] 2019-07-04 10:48
This can be caused by 

* An other program already connected with the mouse (like the officiel Steelseries Enine 3)
* A permission issue (the current user cannot open the device).

I never tested this application on Mac OS and I have no Mac to make test, so I will not be very helpful... :(

**Comment by flozz** [comment] 2020-02-05 12:39
I close this issue, but feel free to answer if you have more information

**Closed by flozz** 2020-02-05 12:39 UTC
